### ISSUE TITLE
Injecting Post Middleware is broken in Vite v3 

### ISSUE THREAD

**Issue by nwaughachukwuma** [ebeloded/vite-plugin-redirect#2]
> **Injecting Post Middleware**
>
> The configureServer hook is called before internal middleware are installed, so the custom middleware will run before internal middleware by default. If you want to inject a middleware after internal middleware, you can return a function from configureServer, which will be called after internal middleware are installed:

Injecting the middleware after internal middleware doesn't work in Vite v3 which was released earlier this month. The fix is to call it before before internal middleware are installed.

```js
/** @return {import('vite').PluginOption} */
const redirect = (redirectMap) => ({
  name: 'redirect',
  configureServer: (server) => {
    server.middlewares.use((req, res, next) => {
      if (redirectMap[req.url]) {
        res.statusCode = 307
        res.setHeader('Location', redirectMap[req.url])
        res.setHeader('Content-Length', '0')
        res.end()
      } else {
        next()
      }
    })
  },
})
```

**Comment by dennisregalado** [comment]
Any possibility on getting this merged via PR?

**Comment by nwaughachukwuma** [comment]
#3 should take care of it when it gets merged.

**Comment by nwaughachukwuma** [comment]
@ebeloded any chance this gets merged soon?

**Comment by zhendalf** [comment]
Thanks for the fix @nwaughachukwuma!

**Comment by nwaughachukwuma** [comment]
🙌🏾
